### ISSUE TITLE
An error while running Mouse-cerebellum.ipynb

### ISSUE THREAD

**Issue by kuang-da** [messcode/STAMarker#1]
Hi,

Thanks for such nice work! I meet a problem while running your `Mouse-cerebellum.ipynb` tutorial. More specifically, it is about the second box under `Visualize spatial domains`.  The error is as follows.

```
TypeError: '(slice(None, None, None), (0, 1))' is an invalid key
```

A screenshot of the error is attached as well. After some googling, it might be about some slicing error, but I could not locate the culprit. I wonder if you know what could be the reason? 

Thank you!

![image](https://user-images.githubusercontent.com/18092300/216238182-be781e95-0bad-4e56-8d53-46fb2a64a47f.png)

**Comment by kuang-da** [comment]
Not very sure how to fix `sc.pl.embedding`, but the following code snippet can be used as an alternative.  

```
import seaborn as sns
import pandas as pd

plot_df = pd.DataFrame(ann_data.obsm["spatial"])
plot_df = plot_df.rename(columns={
    0:'X',
    1:'Y'
})
plot_df['Consensus clustering'] = list(ann_data.obs['Consensus clustering']).copy()
sns.scatterplot(plot_df, x='X', y='Y', hue='Consensus clustering')
```

**Comment by messcode** [comment]
Hi Kuang-da, sorry for the late reply. 
I believe it is the change of the SCANPY version that caused this problem. I converted the `spatial`  to `numpy.ndarray` and fixed this problem.

![image](https://user-images.githubusercontent.com/7353095/227078770-6ff658b1-a1fc-46b1-b6df-3fc38982343f.png)
