### ISSUE TITLE
Missing necessary libraries and versions in requirements.txt

### ISSUE THREAD

**Issue by mejasmi** [messcode/STAMarker#2]
Sklearn and skmisc should have full names (scikit-learn and scikit-misc) so requirements.txt can be automatically run for installation.
Missing torch-sparse package and its version.
Missing scanpy package and its version.
Missing upsetplot package and its version.

**Comment by messcode** [comment]
Hi mejasmi, thank you very much for your comments. I have updated the `requirements.txt`. 

Thank you for bringing this to my attention, and please let me know if you have any further concerns or issues that need to be addressed.
