### ISSUE TITLE
Is calculating both row and col_linkage necessary?

### ISSUE THREAD

**Issue by mejasmi** [messcode/STAMarker#3]
https://github.com/messcode/STAMarker/blob/02f3b195fd6df7e259937ad2e6e667b9042b2461/stamarker/utils.py#L18

Is it necessary to calculate both row and col_linkage since the matrix cmat is symmetric?
col_linkage should be identical to row_linkage, and the function hierarchy.linkage is very slow for larger number of observations.

Also, col_linkage is used only for creation of the image, it is not used in the rest of the code.

**Comment by messcode** [comment]
Hi mejasmi

You are aboslutely right that there is no need to compute both the col and row linkage. I have updated this file. 

Thank you very much.
