### ISSUE TITLE
Can you speed this up with np.meshgrid?

### ISSUE THREAD

**Issue by mejasmi** [messcode/STAMarker#4]
https://github.com/messcode/STAMarker/blob/02f3b195fd6df7e259937ad2e6e667b9042b2461/stamarker/utils.py#L95

Calling zip and itertools to only create pairs of index for symmetrical matrix seems to be too slow. You can use numpy meshgrid function.

row_indices, col_indices = np.meshgrid(indices, indices, copy=True, sparse=False, indexing='ij')
And then just unravel the index matrices:
mat[row_indices.ravel(), col_indices.ravel()] = 1

**Comment by messcode** [comment]
Hi mejasmi, thank you so much for your valuable suggestion. I appreciate your input. I will make the necessary updates to the code and keep you informed as soon as I have completed the changes.

**Comment by messcode** [comment]
Hi mejasmi, I have re-implemented the `consensus_clustering` by linear sum assignment to accerlerate it (see https://github.com/messcode/STAMarker/blob/d027917ee9bf611725b72c308db3eb0827e4b315/stamarker/utils.py#L113).  Now there is no need to use np.mesh_grid.  Thanks!
