### ISSUE TITLE
CPU only cannot run the tutorial

### ISSUE THREAD

**Issue by mejasmi** [messcode/STAMarker#5]
Please provide some information on writing the model.yaml and trainer.yaml

When using only cpu the tutorial code
if not torch.cuda.is_available():
        config["stagate_trainer"]["gpus"] = None
        config["classifier_trainer"]["gpus"] = None
creates an error in pipeline.py
        if config["stagate_trainer"]["gpus"] > 0:
            torch.cuda.empty_cache()
because None cannot be compared to int.
I suggest setting value to 0 instead of None.

**Comment by messcode** [comment]
Thank you very much.!

I have updated the code and now this notebook can be running with only CPU. 

I also briefly described the configuration files. Please kindly refer to https://github.com/messcode/STAMarker/tree/main/tutorial.
